### ISSUE TITLE
[Bug] 1.15.2 Compatibility with newer versions of Crafttweaker

### ISSUE THREAD

**Issue by mr-poyo** [Mrbysco/LoyaltyRewards#1]
## Client Info
* Minecraft Version: 1.15.2

* Forge Version: 31.2.0
* Mod Version: LoyaltyRewards-1.15-1.0.0.jar
* Java Version: Version 8 Update 251 (build 1.8.0_251-b08)

## Issue Description
LoyaltyRewards script is no longer working on Crafttweaker versions beyond CraftTweaker-1.15.2-6.0.0.17.jar

## Reproduce Steps
1) Install new profile with Latest versions of Forge (recommended version), LoyaltyRewards-1.15-1.0.0.jar, and CraftTweaker-1.15.2-6.0.0.19.jar or higher.
2) Create a simple .zs script for testing rewards.
3) Create a new world in single-player and wait for reward (never comes).  

## Additional Information
I found a crafttweaker discrepancy (maybe related, not sure) so I'll throw that below too:
CraftTweaker-1.15.2-6.0.0.17.jar version works perfectly with my script:
![Works_on_CT17](https://user-images.githubusercontent.com/11811815/82135823-ecb80300-9841-11ea-9a81-79777443436e.PNG)
crafttweakerlog from working scenario (CraftTweaker-1.15.2-6.0.0.17.jar):
![Works_on_CT17-ctlog](https://user-images.githubusercontent.com/11811815/82135846-3a347000-9842-11ea-9198-70577eebbe84.PNG)

In-game screenshot of working scenario (CraftTweaker-1.15.2-6.0.0.17.jar):
![Works_on_CT17-ingame](https://user-images.githubusercontent.com/11811815/82135886-c8a8f180-9842-11ea-96d5-b6f3b257962f.PNG)

Doesn't work after upgrading to newest "Release" version of Crafttweaker (CraftTweaker-1.15.2-6.0.0.24.jar).  
crafttweakerlog from non-working scenario (CraftTweaker-1.15.2-6.0.0.24.jar):
![NotWork_on_CT24-ctlog](https://user-images.githubusercontent.com/11811815/82135941-2fc6a600-9843-11ea-9f2b-f6486126fa30.PNG)

Finally a screenshot in-game with the latest release of Crafttweaker (CraftTweaker-1.15.2-6.0.0.24.jar) of non-working scenario:
![NotWork_on_CT24-ingame](https://user-images.githubusercontent.com/11811815/82135970-b11e3880-9843-11ea-84cd-173dfb7f065d.PNG)

**Comment by Mrbysco** [comment]
Fixed it
